### ISSUE TITLE
Add Latitude and Longitude Attributes to Pet Model and PetSeeds.js

### ISSUE THREAD

**Issue by AhmedGarcia** [jocoso/paws-to-doors#28]
Update the Pet model to include latitude and longitude attributes. These attributes will store the geographical coordinates of the pet's location, which can be used to display a map showing the pet's location.

Modify the seed data to include latitude and longitude values for pets.

//model: 
},
    latitude: {
      type: DataTypes.FLOAT,
      allowNull: true,
    },
    longitude: {
      type: DataTypes.FLOAT,
      allowNull: true,
    },

//seed
 {
      name: 'Bella',
      type: 'Dog',
      breed: 'Labrador Retriever',
      age: 2,
      health_status: 'Healthy',
      description: 'Loves to play fetch.',
      location: 'Los Angeles, CA',
      user_id: 2,
      latitude: 34.0522,
      longitude: -118.2437,
   },

**Comment by jocoso** [comment]
are we still doing this?
