### ISSUE TITLE
 Modify Pet Model to Include Image URL

### ISSUE THREAD

**Issue by AhmedGarcia** [jocoso/paws-to-doors#32]
Update the Pet model to include an image_url attribute. This will store the URL of the pet's image, which will be fetched dynamically from The Dog API and The Cat API.

//add to pet model
 },
    image_url: {
      type: DataTypes.STRING,
      allowNull: true,
    },

**Comment by jocoso** [comment]
This was done already.

**Comment by jocoso** [comment]
@AhmedGarcia 

https://github.com/jocoso/paws-to-doors/pull/35
