### ISSUE TITLE
Update Seed Script to Fetch Pet Images Dynamically

### ISSUE THREAD

**Issue by AhmedGarcia** [jocoso/paws-to-doors#33]
Update the seed script to fetch images from The Dog API and The Cat API and include these images in the pet seed data.

First, require axios in seed.js file so we can fetch info for external APIs

Modify the seed script to fetch dog images from The Dog API.
Modify the seed script to fetch cat images from The Cat API.
Include the fetched image URLs in the pet seed data.

// In seeds/seed.js
const getDogImage =

const getCatImage=

==============================

//THEN  in createPetData we call  the function to get dog or cat image depending on pet, from each pet seed:  

const createPetData = async () => {
  const petData = [
    {
      name: 'Buddy',
      type: 'Dog',
      breed: 'Golden Retriever',
      age: 3,
      health_status: 'Healthy',
      description: 'Friendly and energetic.',
      location: 'New York, NY',
      user_id: 1,
      latitude: 40.7128,
      longitude: -74.0060,
      image_url: await getDogImage(),

**Comment by jocoso** [comment]
@AhmedGarcia Your branch is not currently using any API. Do you want me to implement the calling? Where can I find the documentation? Is it an external API? Or do you want me to add the images to the seed in petseeds.js manually?
