### ISSUE TITLE
Implementing User Authentication

### ISSUE THREAD

**Issue by jocoso** [jocoso/paws-to-doors#6]
- **User Story:** As a user, I want to securely log in and manage my pet adoption information.
- **Acceptance Criteria:**
- - **GIVEN:** I enter my credentials
- - **WHEN:** I submit the login form
- - **THEN:** I am authenticated and logged in.

**Comment by jocoso** [comment]
Reopened as Issue contains crashing bugs and does not fulfill the user story.

**Comment by sickcurse** [comment]
Hey Josh,Cool, thanks for fixing those bugs. Also saw my new assignment, #27.  Best,Marquan WhiteOn Aug 2, 2024, at 10:45 AM, Josh ***@***.***> wrote:﻿
Reopened as Issue contains crashing bugs.
